apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: website
spec:
  gatewayClassName: gateway-class
  listeners:
    - name: http
      protocol: HTTP
      port: 80
    - name: https-website
      protocol: HTTPS
      port: 443
      tls:
        mode: Terminate
